from pathlib import Path

path = Path('templates/tv.html')
text = path.read_text(encoding='utf-8')
marker = 'GP_DOORBELL_ANNOUNCEMENT_ALERT_V1'
if marker in text:
    print('doorbell announcement alert already applied')
    raise SystemExit(0)

text = text.replace(
    "// The police tone is the attention cue; the actual message is generated by\n    // /api/followup-voice and spoken immediately afterward.",
    "// GP_DOORBELL_ANNOUNCEMENT_ALERT_V1\n    // A soft two-note doorbell is the attention cue; the actual message follows immediately afterward.",
    1,
)

text = text.replace(
    "try { window.gpPlayTvPoliceAlert?.(); } catch (_) {}",
    "try { window.gpPlayTvDoorBellAlert?.(); } catch (_) {}",
    1,
)

old = """      // Police-style attention sound belongs on the TV when a new management announcement appears.\n      window.gpPlayTvPoliceAlert = function(){\n        try{\n          const AudioCtx=window.AudioContext||window.webkitAudioContext;\n          if(!AudioCtx) return;\n          const ctx=new AudioCtx();\n          ctx.resume?.();\n          const gain=ctx.createGain(); gain.connect(ctx.destination);\n          gain.gain.setValueAtTime(.0001,ctx.currentTime);\n          gain.gain.exponentialRampToValueAtTime(.22,ctx.currentTime+.03);\n          gain.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+1.55);\n          const osc=ctx.createOscillator(); osc.type='square'; osc.connect(gain);\n          osc.frequency.setValueAtTime(650,ctx.currentTime);\n          osc.frequency.linearRampToValueAtTime(1050,ctx.currentTime+.28);\n          osc.frequency.linearRampToValueAtTime(650,ctx.currentTime+.56);\n          osc.frequency.linearRampToValueAtTime(1050,ctx.currentTime+.84);\n          osc.frequency.linearRampToValueAtTime(650,ctx.currentTime+1.12);\n          osc.frequency.linearRampToValueAtTime(1050,ctx.currentTime+1.4);\n          osc.start();osc.stop(ctx.currentTime+1.58);\n          setTimeout(()=>ctx.close?.(),1900);\n        }catch(_){}\n      };\n"""

new = """      // Soft two-note doorbell for new management announcements.\n      // Generated locally so it does not depend on another audio file or network request.\n      window.gpPlayTvDoorBellAlert = function(){\n        try{\n          const AudioCtx=window.AudioContext||window.webkitAudioContext;\n          if(!AudioCtx) return;\n          const ctx=new AudioCtx();\n          ctx.resume?.();\n          const master=ctx.createGain();\n          master.gain.setValueAtTime(.82,ctx.currentTime);\n          master.connect(ctx.destination);\n          const chime=(frequency,delay,duration,volume)=>{\n            const osc=ctx.createOscillator();\n            const gain=ctx.createGain();\n            const start=ctx.currentTime+delay;\n            osc.type='sine';\n            osc.frequency.setValueAtTime(frequency,start);\n            osc.connect(gain);\n            gain.connect(master);\n            gain.gain.setValueAtTime(.0001,start);\n            gain.gain.exponentialRampToValueAtTime(volume,start+.025);\n            gain.gain.exponentialRampToValueAtTime(.0001,start+duration);\n            osc.start(start);\n            osc.stop(start+duration+.04);\n          };\n          chime(784,0,.62,.25);\n          chime(659,.54,.82,.22);\n          setTimeout(()=>ctx.close?.(),1700);\n        }catch(_){}\n      };\n"""

if old not in text:
    raise SystemExit('Expected police alert block not found')
text = text.replace(old, new, 1)

if 'gpPlayTvPoliceAlert' in text:
    raise SystemExit('Old police alert reference remains')
if 'gpPlayTvDoorBellAlert' not in text or marker not in text:
    raise SystemExit('Doorbell alert patch did not apply correctly')

path.write_text(text, encoding='utf-8')
print('Replaced police alert with soft two-note doorbell')
